name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make deps

    - name: Build pages
      run: make pages

    - name: Upload artifact
      id: upload-pages-artifact
      uses: actions/upload-pages-artifact@v3.0.1
      
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4      
